### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by axellageraldinc** [adibta/android-sqllite#1]

**Comment by adibta** [comment]
Do your best

**Comment by axellageraldinc** [comment]
I really love android and SQL, I'll do my best to contribute to this repository 👍

**Comment by Nsikaktopdown** [comment]
Hello @adibta !, what should we build. I suggest a simple note tasking app

**Comment by akashmahalik** [comment]
I would like to contribute to your repo :)
